services:
  frontend:
  build: .
  portes:
    - "5173:5173"
  volumes:
    - .:/app
    - ?app/node_modules
  environment:
    - CHOKIDAR_USERPOLLING=true  # Garante o hot reload e alguns sistemas.
  stdin_open: true
  tty: true